### ISSUE TITLE
soap.listen

### ISSUE THREAD

**Issue by ebastidas** [zardak/meteor-soap#1]
Thanks for this package zardak! How could we possible use the "soap.listen" function of this nodejs module in Meteor?

**Comment by zardak** [comment]
AFAIK, it is not possible without major changes to node-soap.
_soap.listen_ requires _http.Server_ instance passed to it, and meteor doesn't expose one.
Also, _soap.listen_ will probably break things, if you manage to pass _http.Server_ in
https://github.com/vpulim/node-soap/blob/master/lib/server.js#L51

Connect middleware could be plugged into meteor's [webapp](http://docs.meteor.com/#/full/webapp) package, but node-soap's _soap.listen_ isn't available as middleware. So your best bet would be opening an issue at node-soap and asking for a soap server middleware.
