### ISSUE TITLE
How to route soap requests through a proxy/

### ISSUE THREAD

**Issue by shyaaam** [zardak/meteor-soap#10]
Hi, it seems this one is not documented clearly, so please guide me on how to route all my soap requests through a proxy.
 My proxy host is like "http://username:password@us-east-1-static-hopper.quotaguard.com:9293"

**Comment by shyaaam** [comment]
For a fact, i am using this http package for proxy requests.
https://atmospherejs.com/dandv/http-more

**Comment by zardak** [comment]
It actually is documented in [https://github.com/vpulim/node-soap#soapcreateclienturl-options-callback---create-a-new-soap-client-from-a-wsdl-url-also-supports-a-local-filesystem-path](node-soap). You may pass your custom httpClient that will handle requests.

**Comment by shyaaam** [comment]
Hi yes, i looked there before but the author has just mentioned that in passing. Could you please write a line of code and help me to figure out to how to code that particular function.Its confusing for me. I cant seem to get a response from the author regarding this silly thing and im left in the dark.

**Comment by shyaaam** [comment]
Hi can you help me with the syntax

**Comment by zardak** [comment]
First of all, github issues is a place to report problems with package itself, not to ask "How can i do X" - use stackoverflow next time.

Your best bet would be actually getting `request` module into meteor, and using its `.defaults()` to add proxy configuration.

```
var client = Soap.createClient(WSDL_URL, {
  request: request.defaults({ proxy: PROXY_URL })
});
```

One of the possible ways of requiring arbitrary npm module is to use https://github.com/meteorhacks/npm

**Comment by shyaaam** [comment]
thank you for helping me out. Next time, i will use stackoverflow.
