### ISSUE TITLE
can't create client

### ISSUE THREAD

**Issue by nchudnovets** [zardak/meteor-soap#11]
Hello!
Have an issue and have no idea how to solve it. Please help.
I have to use third party SOAP from my Meteor app.
I have added the package and trying following code in my method:

```
url = 'https://api.okpay.com/OkPayAPI?wsdl'
client = Soap.createClient(url)        
result = client.Account_Check(payer, securityToken, receiver)
```

And have following error when client is creating:
_W20160219-13:23:07.117(0)? (STDERR) /home/ubuntu/.meteor/packages/zardak_soap/.0.2.5.ufxs28++os+web.browser+web.cordova/npm/node_modules/soap/lib/wsdl.js:723
W20160219-13:23:07.117(0)? (STDERR)   **for (var i = 0, child; child = children[i]; i++)** {
W20160219-13:23:07.117(0)? (STDERR)                                          ^
W20160219-13:23:07.119(0)? (STDERR) **TypeError: Cannot read property '0' of undefined**
W20160219-13:23:07.120(0)? (STDERR)     at /home/ubuntu/.meteor/packages/zardak_soap/.0.2.5.ufxs28++os+web.browser+web.cordova/npm/node_modules/soap/lib/wsdl.js:1041:26
_
may be you can help me to solve it?
thanx

**Comment by zardak** [comment]
Are you sure you're not trying to create SOAP client in client-side code?

**Comment by nchudnovets** [comment]
This peace of code is a part of method.
The method is placed in a both-side folder Lib
The method is calling from client side, when user clicks a button

**Comment by zardak** [comment]
https://github.com/zardak/meteor-soap/issues/8#issuecomment-137085724

node-soap isn't packaged for browser use, thus you'll have to create a server-only method.

**Comment by nchudnovets** [comment]
Transferred method to Server folder, but result is the same...

Even if i'm trying to create SOAP client on Meteor.startup, without any client's calls

```
Meteor.startup ->
  url = 'https://api.okpay.com/OkPayAPI?wsdl'  
  client = Soap.createClient(url)
```

I have in my console TypeError: Cannot read property '0' of undefined

**Comment by nchudnovets** [comment]
may be there are some requirements to how server side method should be written? 
Should it use some special wrapper or something like that?
May be you could share any example?

**Comment by zardak** [comment]
First of all, your error is related to [node-soap](https://github.com/vpulim/node-soap), a package wrapped by this one.
I skimmed through documentation and found alternative wsdl definition that works.

```
if (Meteor.isServer) {
  Meteor.startup(function () {
    var client = Soap.createClient("https://api.okpay.com/OkPayAPI?singleWsdl");

    try {
      var result = client.Account_Check({
        'WalletID': 'OK123456789',
        'SecurityToken': '5950F9BDA723ECDF9859AD205412BB44',
        'Account': 'OK987654321'
      });
    } catch(e) {
      console.dir(e);
    }
  });
}
```

This code correctly returns error stating that account doesn't exist.

**Comment by nchudnovets** [comment]
Thank you very much! it works!
You really helped me, thank you!
Regards!
