### ISSUE TITLE
Cannot create client in meteor shell - Error: Soap client creation failed [soap-creation]

### ISSUE THREAD

**Issue by darkverbito** [zardak/meteor-soap#12]
I'm trying to create a soap client in the meteor shell but it is not working.

I added the package to my project via meteor add zardak:soap, then I started up my project by running meteor. I opened another tab and ran meteor shell. 

When I tried to execute the following code:

var url = 'https://vdsm1-lv1.foo.com/communication-server/SSControllerCli?wsdl';
var client = Soap.createClient(url);

I get this error:

Error: Soap client creation failed [soap-creation]
    at Object.Soap.createClient (packages/zardak_soap/client.coffee:18:17)
    at [object Object]:1:-43
    at Script.(anonymous function) [as runInThisContext](vm.js:41:22)
    at /Users/gc/Development/appServer/.meteor/local/build/programs/server/shell-server.js:305:27
    at /Users/gc/.meteor/packages/meteor-tool/.1.1.10.149rvb3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/meteor-promise/fiber_pool.js:33:40

Is there something that makes this not work with meteor shell?

**Comment by zardak** [comment]
Could not reproduce with Meteor 1.3.2.4
Please reopen issue with more details if error persists.
