### ISSUE TITLE
How do I install ursa module so it is noticed by meteor when executing function soap.WSSecurityCert

### ISSUE THREAD

**Issue by yushaUzumo** [zardak/meteor-soap#13]
Is anyone able to help me with this rather related question as it seems WSSecurityCert protocol has been omitted from zardak: soap
http://stackoverflow.com/questions/38683924/how-do-i-install-ursa-module-so-it-is-noticed-by-meteor-when-executing-function

Kindly help me. Thanks

By the way,why is WSSecurityCert omitted from zardak: soap?

**Comment by zardak** [comment]
Updated and published new version that includes `node-soap 0.16.0` with `WSSecurityCert`

`node-soap` has `ursa` as optional dependency since it's famous for breaking too often https://github.com/quartzjer/ursa/issues

Your best bet would be to `Npm.require('ursa')` and hope it builds correctly. Something along the lines:

```
Npm.require('ursa');
var wsSecurity = new Soap.WSSecurityCert(...);
var client = Soap.createClient(url);
client.setSecurity(wsSecurity);
```

**Comment by yushaUzumo** [comment]
Hi ,
Thanks for your help 
I,ve run the following command to install ursa: meteor npm install --save ursa
This created an entry in package.json. I also fowarded my public key to the server administrator so that they include it in their keystore. They also sent me their public key but I don't know where to include it in my code or application
My code is as follows:

`if (Meteor.isServer) {
    Meteor.methods({
        getVouchers: function(){

```
        var fs = Npm.require("fs");
        var soap = Npm.require("soap");
        Npm.require('ursa');
        var base = process.env.PWD;

        var publicKey = fs.readFileSync(base + "/cert.pem", "utf8");
        var privateKey = fs.readFileSync(base + "/key.pem", "utf8");
        var password = "myPassPhrase";

        var url = "http://www.smartcallesb.co.za:8091/SmartcallServices2/SmartloadService?wsdl";

        try
        {
            var wsSecurity = new soap.WSSecurityCert(privateKey, publicKey, password, 'utf8');
            var client = Soap.createClient(url);
            client.setSecurity(wsSecurity);
            //var result = client.SmartloadService.SmartloadServicePort.getDealerBalance(); //getAllNetworks
            var result = client.getDealerBalance();
            console.log(result)
        }
        catch (err)
        {
            console.log(err)
        }
        console.log("reached end")

    }
});
```

}`

When it is run I now get the following error:

{ [Error: Soap method call failed [soap-method]]
    error: 'soap-method',
    reason: 'Soap method call failed',
    reason: 'Soap method call failed',
    details:
        { [Error: soap:Client: Unexpected wrapper element getDealerBalance found.   Expected {http://www.smartcall.co.za/2010/12/service}getDealerBalance.].....  

Could this be because the host public key that the server admin sent to me is not included in my application, and if so where do I include it?

**Comment by zardak** [comment]
Your error is related to `node-soap` itself, not this wrapper. Still, passing following options to SOAP client constructor might help:

```
Npm.require('ursa');
var wsSecurity = new Soap.WSSecurityCert(...);
var options = {
  ignoredNamespaces: {
    namespaces: [],
    override: true
  }
};
var client = Soap.createClient(url, options);
client.setSecurity(wsSecurity);
```

**Comment by yushaUzumo** [comment]
Thanks for your help. I tried including the options but I just get another error.

**Comment by yushaUzumo** [comment]
Hi ,
Sorry to bother you man. I've looked everywhere on the web for this issue but can't find the solution the error I am now getting after including the options as per your suggestion is:

details: { [Error: soap:Server: These policy alternatives can not be satisfied: 

 { [Error: soap:Server: These policy alternatives can not be satisfied: 
{ [Error: Soap method call failed [soap-method]]
I20160808-17:16:50.584(2)?   error: 'soap-method',
I20160808-17:16:50.584(2)?   reason: 'Soap method call failed',
I20160808-17:16:50.585(2)?   details: 
I20160808-17:16:50.585(2)?    { [Error: soap:Server: These policy alternatives can not be satisfied: 
I20160808-17:16:50.586(2)?    {http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}AsymmetricBinding: The transform algorithms do not match the requirement
I20160808-17:16:50.587(2)?    {http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}InitiatorToken
I20160808-17:16:50.587(2)?    {http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}RecipientToken
I20160808-17:16:50.589(2)?    {http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}IncludeTimestamp
I20160808-17:16:50.590(2)?    {http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}EncryptedParts: {http://schemas.xmlsoap.org/soap/envelope/}Body not ENCRYPTED]
.......

Please help.

The previous error before your suggestion, it seems it was mourning about the namespace in the wsdl: http://www.smartcallesb.co.za:8091/SmartcallServices2/SmartloadService?wsdl . So I take it your suggestion tells soap to ignore the namespace
