### ISSUE TITLE
how to use the server part of zardak:soap

### ISSUE THREAD

**Issue by vinaykaran** [zardak/meteor-soap#14]
I tried this module and was able to get values out of a wsdl end point by calling the url. Next i tried the soap server part but did not know how to proceed.
I was trying to host a wsdl but am not sure how to use it.
I have a soap xml file in my server which i am trying to expose as a wsdl using zardak soap. 

I am not sure what URL to use to get the book author. I know i have to put the book id and get the book author 

My code on server start up is 

```
        var service = {
           Catalog: {
             3000: {   // i don't know what MyPort is. I just added the default port my application is on.

                GetAuthor: function(args) { // GetAuthor is MyOperation
                  if(!args.Request) {
                  throw { Fault: {
                        Code: {
                          Value: "soap:Sender",
                          Subcode: { value: "rpc:BadArguments" }
                        },
                         Reason: { Text: "Processing Error" }
                     } };
                  }
                    console.log("asdf"+ args.Request);
                  return { Response: args.Request };  // will this give my book author value?
                }

              }
              }
         };

          var wsdl = Assets.getText('wsdl.xml');  //this is my soap xml file
          var soapServer = Soap.listen('/soap', service, wsdl);
```

**Comment by zardak** [comment]
Refer to this example
https://github.com/zardak/meteor-soap/blob/master/tests/data.js#L12-L79

Your service definition has to correspond to WSDL. The data-processing part is totally unrelated to this package, better use stackoverflow for questions.
