### ISSUE TITLE
Seems to hang in 1.4.1

### ISSUE THREAD

**Issue by gerwinbrunner** [zardak/meteor-soap#15]
Hi,

when I use create a client like this in meteor 1.4.1
`var client = Soap.createClient(url);`
The app stops at that point and waits till the request times out after 60 seconds with:

```
I20160820-13:14:04.162(2)? SOAP Error { [Error: Soap client creation failed [soap-creation]]
I20160820-13:14:04.169(2)?   error: 'soap-creation',
I20160820-13:14:04.170(2)?   reason: 'Soap client creation failed',
I20160820-13:14:04.170(2)?   details: { [Error: socket hang up] code: 'ECONNRESET' },
I20160820-13:14:04.170(2)?   message: 'Soap client creation failed [soap-creation]',
I20160820-13:14:04.170(2)?   errorType: 'Meteor.Error' }
```

It seems that this line is causing it... 

```
Meteor.wrapAsync(Soap.createClient, Soap).apply(null, arguments);
```

Any idea what is wrong?

**Comment by zardak** [comment]
Are you actually sure that your `url` is valid?
The `[Error: socket hang up] code: 'ECONNRESET'` part means that server didn't respond.

**Comment by gerwinbrunner** [comment]
Yes, using the async function works. So I guess the url is fine.

Mit freundlichen Grüßen
Gerwin Brunner

**Comment by zardak** [comment]
Can't seem to reproduce it myself and tests are still passing on `1.4.1`. Please provide sample code to reproduce this behaviour.

**Comment by gerwinbrunner** [comment]
@zardak When I created a project to reproduce the problem I got closer to what it actually causes it. 

Here is the sample:
https://github.com/Vilango/meteor-soap-sample

The issue with the not responding client occurs when I try to fetch the xml from a public folder within the meteor app. This does not work.
The same xml fetched from a remote url works fine.

Just switch the comments in those lines to use the remote wsdl file and all works:
https://github.com/Vilango/meteor-soap-sample/blob/master/server/main.js#L6-L7

Hmmm... 
It seems that the the soap client call to itself blocks meteor and so it can't deliver the file it actually needs to continue. Really wired. 

I'm not sure how this would be fixable. But it would be nice to have locally hosted wsdl files.

**Comment by zardak** [comment]
Looks like you need to use `Assets.absoluteFilePath(assetPath)` when specifying relative paths to file - https://docs.meteor.com/api/assets.html#Assets-absoluteFilePath

Read through the docs carefully, as 

> Static server assets are included by placing them in the application’s private subdirectory.

**Comment by gerwinbrunner** [comment]
oh true... this way it works. Thanks!
