### ISSUE TITLE
soap client opening multiple sockets for multiple method calls

### ISSUE THREAD

**Issue by vinaykaran** [zardak/meteor-soap#16]
Hi Zardak, 
Sorry to raise this here, i wasn't getting any help on stackoverflow.
I was able to create a client and then call a custom soap server and works nicely. 

But what i noted is that the client opens a socket, calls the method, gets back the result and closes the socket connection. The client opens a new socket when it calls another method

I used client.method(args,{keepAlive:true}) which keeps the socket open, however on the second method call client still creates a new socket connection. How can i use only a single socket connection and call multiple methods?

I would appreciate any help

**Comment by zardak** [comment]
Seems like you need to add

```
headers: {
  connection: 'keep-alive'
}
```

to your request.

**Comment by vinaykaran** [comment]
My current code is like below which creates 2 sockets for 2 of my function calls and keeps them both live because of the keepAlive parameter in the options variable. I want only one socket opened and be used for all of my function calls.

```
var options = { 
  keepAlive:true,
}
var client = Soap.createClient(url, options);
var result = client.wsdlservice.portmyfirstfunction(args,options);
//process the result
result = client.wsdlservice.port.mysecondfunction(args,options);
```

Should i add the below statement
`client.addSoapHeader({connection:'keep-alive'})`
 before calling my functions or should i add the connection parameter in the options variable?

**Comment by zardak** [comment]
It's the HTTP header, not the SOAP one, so parameter goes to `options` variable for each method call.

Sorry, this package is only the wrapper of
https://github.com/vpulim/node-soap
which uses
https://github.com/request/request
for http(s) requests. Maybe you should look into them.

**Comment by vinaykaran** [comment]
Thank you Zardak, 
This worked. I also had to add a keepaliveagent and set the maxsocketes and assign it to the agent parameter along with the headers connection parameter.

import KeepAliveAgent from 'keep-alive-agent';
var agent = new KeepAliveAgent({ maxSockets: 1 });

var options = {
  agent:agent,
  headers: {"Connection":"Keep-Alive"}
}

**Comment by vinaykaran** [comment]
The above solution to reuse a single socket connection works only for http but not for https.
i have not found a solution on how to handle reusing sockets in https. If you come across please share.
