### ISSUE TITLE
Server mode not supported

### ISSUE THREAD

**Issue by Xample** [zardak/meteor-soap#2]
Hi, I know this is not a bug but just a current limitation. My question is : Are you planning to support the server mode later ? [It seems I am not alone to wonder how to achieve this](http://stackoverflow.com/questions/27970013/how-can-i-use-node-soap-in-meteorjs#comment46660161_27970013)
Thank you

**Comment by zardak** [comment]
Hello. Someone did already ask about this. Sadly, its not possible atm without major changes to node-soap.
https://github.com/zardak/meteor-soap/issues/1#issuecomment-76968717
