### ISSUE TITLE
client undefined

### ISSUE THREAD

**Issue by ffxsam** [zardak/meteor-soap#5]
For some reason, I'm getting an exception at this line:

https://github.com/zardak/meteor-soap/blob/master/client.coffee#L22

client is undefined. How exactly would this happen?

**Comment by zardak** [comment]
Could you please provide the code which causes it fail?

**Comment by ffxsam** [comment]
I figured it out - no problem! :)

**Comment by ronlinet** [comment]
Nice, how about to contribute with solution ?

**Comment by Noveltysa** [comment]
@ffxsam .......2. how about contributing with your solution ?

**Comment by ffxsam** [comment]
Oh man, it's been months. I'm not even using SOAP anymore, so I don't remember what the solution was. The solution was to eventually stop using SOAP. :)
