### ISSUE TITLE
"H E L P" Error: Cannot parse response

### ISSUE THREAD

**Issue by Hamatek** [zardak/meteor-soap#6]
Hello,

I have been trying to work my way with Meteor-soap/node-soap for hourssss but I wasn't able to figure out why every time I call a method I get : Error: Cannot parse response .

When create Client without any options : `Soap.createClient(url)`
It seems the  to be working  properly since `client.describe()` 
return all the method of my WSDL 

to call my method I use this syntax `Client.service.port.method(args)`

Also I know that the SOAP Webservice works fine because I have it run in production on a PHP website and I use tool like SOAPUI 5, they both work perfectly without any special options.

What might be wrong is that maybe I may be missing some options ? When I create client or call method ? OR Maybe it's something related to the `client.service.port.method` syntax rather than just `client.MyFunction(args)` ? ...

I really am clueless about how to debug this soap response issue, any help would be greatly appreciated !

**Comment by zardak** [comment]
Hello.

Looks like your issue is related to [node-soap](https://github.com/vpulim/node-soap) rather than to this package. Please consider filing an issue there. Also, providing samples of your WSDL and response from server or the link to server itself would greatly help with debugging.
