### ISSUE TITLE
Can't create create a new SOAP client from a WSDL url

### ISSUE THREAD

**Issue by ronlinet** [zardak/meteor-soap#8]
I have installed this package with all dependancies and the 'Soap.create' method stuck with error :

```
ReferenceError: Soap is not defined meteor-soap.js:12:4
```

The code :

``` javascript
      Session.setDefault('spcnt', 'empty so far');
      Template.soap.helpers({ spcnt: function () { return Session.get('spcnt'); } });

      Template.soap.events({

          //kicking off the soap 
         'click .getVal': function (event, template) {
             Soap.createClient('http://www.webservicex.net/geoipservice.asmx?WSDL');         

      });
}

})();
```

**Comment by zardak** [comment]
[`node-soap`](https://github.com/vpulim/node-soap), and thus `meteor-soap` are server-side only packages, so `Soap` is expected to be `undefined` client-side. I guess `node-soap` won't be packaged as client-side lib anytime soon, so there's nothing I can do.

You might want to do all `Soap` related stuff server-side and then supply the response to client.

Thanks for filing an issue, seems like this needs a mention in docs.

**Comment by ronlinet** [comment]
Thx for your feedback. 
Regards.
